### ISSUE TITLE
mahalle kasaba

### ISSUE THREAD

**Issue by Tezcan98** [ubeydeozdmr/turkiye-api#13]
Elinize sağlık güzel bir çalışma olmuş. Kasaba ve mahalleleri de ekleseniz süper olurdu

**Comment by ubeydeozdmr** [comment]
Teşekkür ederim 🙂 @Tezcan98 

> Kasaba ve mahalleleri de

Biraz zaman alacak ama bunu da yapmaya çalışacağım. Öneriniz için teşekkürler

**Comment by ubeydeozdmr** [comment]
Evet biraz geç de olsa sonunda ekleyebildim :)
