### ISSUE TITLE
Yanlış ilçe ismi

### ISSUE THREAD

**Issue by detmach** [ubeydeozdmr/turkiye-api#14]
![image](https://github.com/ubeydeozdmr/turkiye-api/assets/7414508/0312bda8-eb5f-4da7-912e-c543df0a184f)

Boldavin diye geçmiş sisteminizde. 

![image](https://github.com/ubeydeozdmr/turkiye-api/assets/7414508/78835010-c731-4c39-ad04-f225c32793b7)

**Comment by ubeydeozdmr** [comment]
Uyarınız için teşekkürler, bakacağım
