### ISSUE TITLE
Sadece illeri çekme

### ISSUE THREAD

**Issue by volkankoc** [ubeydeozdmr/turkiye-api#16]
Merhabalar çalışmanız için teşekkür ederim. 
Bir ricam olacaktı https://turkiyeapi.cyclic.app/api/v1/provinces bu istek ile tüm dataları çekiyoruz. Ama ben buradaki il bilgisini kullanıyorum ve o şekilde devam ediyorum.

Acaba sadece illerin listesini ve id sini çekecek bir parametre eklermisiniz

teşekkürler

**Comment by ubeydeozdmr** [comment]
@volkankoc 

https://turkiyeapi.cyclic.app/api/v1/provinces?fields=id,name

**Comment by ubeydeozdmr** [comment]
> Merhabalar çalışmanız için teşekkür ederim.

ne demek

fields parametresini kullanabilirsiniz. "?fields=" kısmından itibaren her field'ın arasında bir virgül olmalı

**Comment by volkankoc** [comment]
> ubeydeozdmr

Aslında dokümantasyonu bayağı inceledim yine de gözümden kaçmış. Çok güzel bir çalışma olmuş tekrar teşekkürler

**Comment by ubeydeozdmr** [comment]
> > ubeydeozdmr
> 
> Aslında dokümantasyonu bayağı inceledim yine de gözümden kaçmış. Çok güzel bir çalışma olmuş tekrar teşekkürler

Rica ederim tekrardan 🙂
