### ISSUE TITLE
belde / kasaba bilgileri

### ISSUE THREAD

**Issue by unicorn64** [ubeydeozdmr/turkiye-api#29]
Öncelikle elinize emeğinize sağlık. çok güzel bir çalışma olmuş.

Belde / kasaba bilgilerini eklemeniz mümkün mü?
kapatılan #13 nolu maddede sanırım mahalleler eklenmiş, belde/kasaba bilgileri dahilse de ben veri olarak göremedim. 
Veri kaynağı olarak [Mülkü İdari Birimler](https://www.e-icisleri.gov.tr/Anasayfa/MulkiIdariBolumleri.aspx) sayfası kullanılabilir sanırım

İlginize teşekkürler

**Comment by ubeydeozdmr** [comment]
> Öncelikle elinize emeğinize sağlık. çok güzel bir çalışma olmuş.

Ne demek ben teşekkür ederim

> Belde / kasaba bilgilerini eklemeniz mümkün mü?

Aslında mahalle/köy verilerini API'a geç ekledim, eklerken beldeleri eklemeyi de düşünmedim değil ancak bu sefer hem kod hem API çok karışacaktı (hem veritabanı kullanmadığım için hem de baştan planlamayı eksik-basit yapmamdan kaynaklı)
Yine de beldeleri belirli/kesin bir zaman veremesem de eklemeyi düşünüyorum, v2 sürümüyle birlikte çıkarmayı düşünüyorum, bununla birlikte buna gerek kalmadan direkt v1 sürümünde de ekleyebilirim ancak bu durumda muhtemelen diğer şemalardan (il, ilçe, mahalle, köy) izole olur gibi. Bunu (beldeleri) muhtemelen ekleyebilirim.

Kasaba kısmını tam anlayamadım. Burada kastettiğiniz şey attığınız linkteki bağlılar mı? Kaynak olarak [https://biruni.tuik.gov.tr/medas/](https://biruni.tuik.gov.tr/medas/) kullanmaktayım, bunun idari birimlerde net bir karşılığı yok gibi. Bununla birlikte (eğer kastettiğiniz bağlılar ise) il-ilçe gibi küçük veriler için değil ancak mahalle-köy gibi büyük veri tablolarında tek tek yazmak yerine bir miktar kod yazıp işi otomasyona bağlıyorum, bunun için TÜİK Medas'ın sunduğu Excel tablosu işlevli ancak İçişleri bakanlığının excel tablolarında hem ID bilgileri eksik hem de bağlıya ait il ilçe bilgileri sütunlara doğru ayrılmamış. Bu şemaları bağlama açısından (özellikle ID'lerin eksikliğinden kaynaklı) çok uğraştırır maalesef ki.

**Comment by unicorn64** [comment]
Aslında kasaba dediğim de belde'ye karşılık geliyor olmalı. önceden ilçeye bağlı belediyesi olan alt yerleşime kasaba da deniyordu sanırım. bazı eski kaynaklarda bu şekilde geçiyor olabilir hala. bir de #13 nolu talepte de mahalle kasaba ifadesi kullanıldığı için o şekilde yazmıştım. 
yani aslında kasdettiğim beldeler. ayrı servis olarak en azından hangi ilçenin beldesi olduğunu anlamak adına districtId içerecek şekilde sunulabilse o da yeterli olur sanırım.

(bu arada önceki gönderdiğim listedeki bağlılar listeleri köyün mahalleleri anladığım kadarıyla, o baya bi detay olur zaten mevcut yapınızda)

**Comment by ubeydeozdmr** [comment]
> bir de https://github.com/ubeydeozdmr/turkiye-api/issues/13 nolu talepte de mahalle kasaba ifadesi kullanıldığı için o şekilde yazmıştım.

Evet #13 numaralı meselede eklenen şeyin mahalleler ve köyler olduğunu bildirmem gerekiyordu.

> yani aslında kasdettiğim beldeler. ayrı servis olarak en azından hangi ilçenin beldesi olduğunu anlamak adına districtId içerecek şekilde sunulabilse o da yeterli olur sanırım.

Sanırım bunu v1 üzerinde ve daha kısa sürede yapabilirim. Buna bakacağım

Önerileriniz için teşekkür ederim @unicorn64
