### ISSUE TITLE
Posta kodları

### ISSUE THREAD

**Issue by HakanKorkz** [ubeydeozdmr/turkiye-api#30]
Elinize emeğinize sağlık acaba şehirlerin posta kodlarını eklemeyi düşünüyor musunuz?

**Comment by ubeydeozdmr** [comment]
> Elinize emeğinize sağlık

Ne demek ben teşekkür ederim

> acaba şehirlerin posta kodlarını eklemeyi düşünüyor musunuz?

Evet, hatta bunu mahalle/köy verilerini eklemeden önce eklemeyi düşünüyordum. Neden hala eklemedim onu da düşünüyorum. Sanırım müsait bir zamanda v2 sürümünü çıkmaya gerek kalmadan v1 içerisinde halledebilirim, her ne kadar kesin bir tarih veremesem de. Eklediğimde bilgilendireceğim, öneriniz için teşekkür ederim.

**Comment by ubeydeozdmr** [comment]
İyi günler,

Sanırım geç ve eksik de olsa iller ve ilçelerin tamamı için posta kodlarını ekledim, `activatePostalCodes=true` yaparak posta kodlarına ulaşabilirsiniz.

Mahalle ve köyler için: ( Issue: #38 )
